### PR TITLE
Add jsoncpp 1.8.3 to project

### PR DESCRIPTION
**Pull request by patternoia**

### CODE REVIEW

**Comment by denisbertini** [comment]
CMake Error in dbase/db3rdParty/jsoncpp/src/lib_json/CMakeLists.txt:
  Target "jsoncpp_lib_static" requires the language dialect "CXX11" , but
  CMake does not know the compile flags to use to enable it.

**Comment by denisbertini** [comment]
i have the follwing problem with your  last pull request, do you have an idea what is this CXX11 about ?

**Comment by patternoia** [comment]
Not sure, it works on my side just fine.

my compilation command is simple:
export SIMPATH=~/FairSoft; cmake .. -DCMAKE_INSTALL_PREFIX=~/FairRoot -DWITH_DBASE=ON && make -j4 install

Other project items, that require C++11 detect it normally.

**Comment by denisbertini** [comment]
humm which cmake version you have?

**Comment by patternoia** [comment]
cmake version 3.7.2

**Comment by denisbertini** [comment]
oho i have cmake version 3.1

**Comment by patternoia** [comment]
cmake 3.7.2 is installed by FairSoft by default

**Comment by patternoia** [comment]
I think it is safe then to assume a cmake version that high in other FairRoot projects

**Comment by denisbertini** [comment]
I am doing a clean installation removing cmake cache now  ... let see...

**Comment by patternoia** [comment]
However, jsoncpp requires `CMAKE_MINIMUM_REQUIRED(VERSION 3.1)`
meaning it should work on your side

**Comment by denisbertini** [comment]
It is a bug in cmake 3.1 for macosx ... upgrading my cmake right now ...

**Comment by denisbertini** [comment]
It compiles with cmake 3.9 on my Mac now

**Comment by denisbertini** [comment]
but linking FairDb.so i got this 
ld: library not found for -ljsoncpp
looks like json part is not compiled ... i will have further look

**Comment by patternoia** [comment]
Why is a .so file being linked?

In my case dylibs get compiled with no error:
Linking CXX shared library ../lib/libFairDB.dylib

**Pull request merged**
