### PR TITLE
Configure jsoncpp options before building

### PR DESCRIPTION
**Pull request by patternoia**
Turns off tests and builds a dynamic lib

### CODE REVIEW

**Comment by denisbertini** [comment]
The problem is linked to the fact that the library prefix "dylib" is NOT recognized by CMake eventhough the library is in /lib jsoncpp.dylib.  How to change this .dylib to standard .so ?

**Comment by denisbertini** [comment]
Nop, putting a soft link manually to libjsoncpp.so did not help !

**Comment by denisbertini** [comment]
of course not since the 2 format are not compatible ! so my basic problem is that json-lib is created with -dynamiclib

**Comment by patternoia** [comment]
Puzzling. On osx it seems that cmake will always link dylibs when `ADD_LIBRARY` is invoked with `SHARED` option. The .so libs created in FairSoft lib dirs are just symbolic links to dylibs according to zmq installation script.
```
    if [ "$platform" = "macosx" ];
    then
      cd $install_prefix/lib
      create_links dylib so
    fi
```
Anyway why do you need .so libs on your osx machine?

**Comment by denisbertini** [comment]
yep it should in principle work but something went wrong in my case ... i will recreate everything from scratch --- let see

**Comment by patternoia** [comment]
Hi, have you succeeded compiling everything?

**Comment by denisbertini** [comment]
still in process i will tell you when i will finish ...

________________________________

**Pull request merged**
